# Generated by Django 5.1.4 on 2024-12-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_remove_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
